$(window).scroll(function(){
        if($(this).scrollTop()>50)
        {
          $(".bg-lighta").addClass("red")
        }
        else
        {
          $(".bg-lighta").removeClass("red")
        }
      })